# See the documentation for more information:
# https://packit.dev/docs/configuration/

---

specfile_path: resalloc-ibm-cloud.spec
upstream_package_name: resalloc-ibm-cloud
downstream_package_name: resalloc-ibm-cloud
upstream_project_url: https://github.com/fedora-copr/resalloc-ibm-cloud


files_to_sync:
  - resalloc-ibm-cloud.spec
  - .packit.yaml


srpm_build_deps:
  - python3-setuptools_scm

jobs:
  - job: copr_build
    trigger: pull_request
    targets:
      - fedora-all

  - job: copr_build
    trigger: commit
    branch: main
    targets:
      - fedora-all
    project: resalloc-ibm-cloud
    list_on_homepage: True
    preserve_project: True
